// Auto-generated token types — do not edit directly
export type DesignToken = 
  | '--ds-black-0'
  | '--ds-black-100'
  | '--ds-black-1000'
  | '--ds-black-150'
  | '--ds-black-200'
  | '--ds-black-300'
  | '--ds-black-400'
  | '--ds-black-50'
  | '--ds-black-500'
  | '--ds-black-600'
  | '--ds-black-700'
  | '--ds-black-750'
  | '--ds-black-800'
  | '--ds-black-850'
  | '--ds-black-900'
  | '--ds-black-950'
  | '--ds-black-transparent'
  | '--ds-blue-ribbon-100'
  | '--ds-blue-ribbon-200'
  | '--ds-blue-ribbon-300'
  | '--ds-blue-ribbon-400'
  | '--ds-blue-ribbon-50'
  | '--ds-blue-ribbon-500'
  | '--ds-blue-ribbon-600'
  | '--ds-blue-ribbon-700'
  | '--ds-blue-ribbon-800'
  | '--ds-blue-ribbon-900'
  | '--ds-blue-ribbon-950'
  | '--ds-border-brand-color'
  | '--ds-border-brand-color-disabled'
  | '--ds-border-danger-color'
  | '--ds-border-neutral-light-color'
  | '--ds-border-neutral-soft-color'
  | '--ds-coral-red-100'
  | '--ds-coral-red-200'
  | '--ds-coral-red-300'
  | '--ds-coral-red-400'
  | '--ds-coral-red-50'
  | '--ds-coral-red-500'
  | '--ds-coral-red-600'
  | '--ds-coral-red-700'
  | '--ds-coral-red-800'
  | '--ds-coral-red-900'
  | '--ds-coral-red-950'
  | '--ds-jade-100'
  | '--ds-jade-200'
  | '--ds-jade-300'
  | '--ds-jade-400'
  | '--ds-jade-50'
  | '--ds-jade-500'
  | '--ds-jade-600'
  | '--ds-jade-700'
  | '--ds-jade-800'
  | '--ds-jade-900'
  | '--ds-jade-950'
  | '--ds-pizazz-100'
  | '--ds-pizazz-200'
  | '--ds-pizazz-300'
  | '--ds-pizazz-400'
  | '--ds-pizazz-50'
  | '--ds-pizazz-500'
  | '--ds-pizazz-600'
  | '--ds-pizazz-700'
  | '--ds-pizazz-800'
  | '--ds-pizazz-900'
  | '--ds-pizazz-950'
  | '--ds-surface-brand-color'
  | '--ds-surface-brand-color-active'
  | '--ds-surface-brand-color-hover'
  | '--ds-surface-brand-light-color'
  | '--ds-surface-brand-pale-color'
  | '--ds-surface-danger-color'
  | '--ds-surface-danger-pale-color'
  | '--ds-surface-neutral-light-color'
  | '--ds-surface-neutral-light-color-active'
  | '--ds-surface-neutral-light-color-disabled'
  | '--ds-surface-neutral-light-color-hover'
  | '--ds-surface-neutral-pale-color'
  | '--ds-surface-neutral-pale-color-hover'
  | '--ds-surface-overlay-static-color'
  | '--ds-surface-pure-color'
  | '--ds-surface-success-color'
  | '--ds-surface-success-pale-color'
  | '--ds-surface-transparent-color'
  | '--ds-surface-warning-color'
  | '--ds-text-brand-color'
  | '--ds-text-brand-color-active'
  | '--ds-text-brand-color-disabled'
  | '--ds-text-brand-color-hover'
  | '--ds-text-color'
  | '--ds-text-color-disabled'
  | '--ds-text-inversed-color'
  | '--ds-text-inversed-static-color'
  | '--ds-text-soft-color'
  | '--ds-text-static-color';

export type Theme = 'light' | 'dark' | 'system';

export interface ThemeTokens {
  black_0: string;
  black_100: string;
  black_1000: string;
  black_150: string;
  black_200: string;
  black_300: string;
  black_400: string;
  black_50: string;
  black_500: string;
  black_600: string;
  black_700: string;
  black_750: string;
  black_800: string;
  black_850: string;
  black_900: string;
  black_950: string;
  black_transparent: string;
  blue_ribbon_100: string;
  blue_ribbon_200: string;
  blue_ribbon_300: string;
  blue_ribbon_400: string;
  blue_ribbon_50: string;
  blue_ribbon_500: string;
  blue_ribbon_600: string;
  blue_ribbon_700: string;
  blue_ribbon_800: string;
  blue_ribbon_900: string;
  blue_ribbon_950: string;
  border_brand_color: string;
  border_brand_color_disabled: string;
  border_danger_color: string;
  border_neutral_light_color: string;
  border_neutral_soft_color: string;
  coral_red_100: string;
  coral_red_200: string;
  coral_red_300: string;
  coral_red_400: string;
  coral_red_50: string;
  coral_red_500: string;
  coral_red_600: string;
  coral_red_700: string;
  coral_red_800: string;
  coral_red_900: string;
  coral_red_950: string;
  jade_100: string;
  jade_200: string;
  jade_300: string;
  jade_400: string;
  jade_50: string;
  jade_500: string;
  jade_600: string;
  jade_700: string;
  jade_800: string;
  jade_900: string;
  jade_950: string;
  pizazz_100: string;
  pizazz_200: string;
  pizazz_300: string;
  pizazz_400: string;
  pizazz_50: string;
  pizazz_500: string;
  pizazz_600: string;
  pizazz_700: string;
  pizazz_800: string;
  pizazz_900: string;
  pizazz_950: string;
  surface_brand_color: string;
  surface_brand_color_active: string;
  surface_brand_color_hover: string;
  surface_brand_light_color: string;
  surface_brand_pale_color: string;
  surface_danger_color: string;
  surface_danger_pale_color: string;
  surface_neutral_light_color: string;
  surface_neutral_light_color_active: string;
  surface_neutral_light_color_disabled: string;
  surface_neutral_light_color_hover: string;
  surface_neutral_pale_color: string;
  surface_neutral_pale_color_hover: string;
  surface_overlay_static_color: string;
  surface_pure_color: string;
  surface_success_color: string;
  surface_success_pale_color: string;
  surface_transparent_color: string;
  surface_warning_color: string;
  text_brand_color: string;
  text_brand_color_active: string;
  text_brand_color_disabled: string;
  text_brand_color_hover: string;
  text_color: string;
  text_color_disabled: string;
  text_inversed_color: string;
  text_inversed_static_color: string;
  text_soft_color: string;
  text_static_color: string;
}
