// Auto-generated token types — do not edit directly
export type DesignToken = 
  | '--ds-black-0'
  | '--ds-black-100'
  | '--ds-black-1000'
  | '--ds-black-150'
  | '--ds-black-200'
  | '--ds-black-300'
  | '--ds-black-400'
  | '--ds-black-50'
  | '--ds-black-500'
  | '--ds-black-600'
  | '--ds-black-700'
  | '--ds-black-750'
  | '--ds-black-800'
  | '--ds-black-850'
  | '--ds-black-900'
  | '--ds-black-950'
  | '--ds-black-transparent'
  | '--ds-blue-ribbon-100'
  | '--ds-blue-ribbon-200'
  | '--ds-blue-ribbon-300'
  | '--ds-blue-ribbon-400'
  | '--ds-blue-ribbon-50'
  | '--ds-blue-ribbon-500'
  | '--ds-blue-ribbon-600'
  | '--ds-blue-ribbon-700'
  | '--ds-blue-ribbon-800'
  | '--ds-blue-ribbon-900'
  | '--ds-blue-ribbon-950'
  | '--ds-border-brand-color'
  | '--ds-border-brand-color-disabled'
  | '--ds-border-danger-color'
  | '--ds-border-neutral-light-color'
  | '--ds-border-neutral-soft-color'
  | '--ds-coral-red-100'
  | '--ds-coral-red-200'
  | '--ds-coral-red-300'
  | '--ds-coral-red-400'
  | '--ds-coral-red-50'
  | '--ds-coral-red-500'
  | '--ds-coral-red-600'
  | '--ds-coral-red-700'
  | '--ds-coral-red-800'
  | '--ds-coral-red-900'
  | '--ds-coral-red-950'
  | '--ds-fontfamilies-inter'
  | '--ds-fontsize-0'
  | '--ds-fontsize-1'
  | '--ds-fontsize-2'
  | '--ds-fontsize-3'
  | '--ds-fontsize-4'
  | '--ds-fontsize-5'
  | '--ds-fontsize-6'
  | '--ds-fontsize-7'
  | '--ds-fontweights-inter-0'
  | '--ds-fontweights-inter-1'
  | '--ds-fontweights-inter-2'
  | '--ds-jade-100'
  | '--ds-jade-200'
  | '--ds-jade-300'
  | '--ds-jade-400'
  | '--ds-jade-50'
  | '--ds-jade-500'
  | '--ds-jade-600'
  | '--ds-jade-700'
  | '--ds-jade-800'
  | '--ds-jade-900'
  | '--ds-jade-950'
  | '--ds-letterspacing-0'
  | '--ds-letterspacing-1'
  | '--ds-letterspacing-3'
  | '--ds-lineheights-0'
  | '--ds-lineheights-1'
  | '--ds-lineheights-2'
  | '--ds-lineheights-3'
  | '--ds-lineheights-4'
  | '--ds-lineheights-5'
  | '--ds-lineheights-6'
  | '--ds-lineheights-7'
  | '--ds-lineheights-8'
  | '--ds-lineheights-9'
  | '--ds-paragraphindent-0'
  | '--ds-pizazz-100'
  | '--ds-pizazz-200'
  | '--ds-pizazz-300'
  | '--ds-pizazz-400'
  | '--ds-pizazz-50'
  | '--ds-pizazz-500'
  | '--ds-pizazz-600'
  | '--ds-pizazz-700'
  | '--ds-pizazz-800'
  | '--ds-pizazz-900'
  | '--ds-pizazz-950'
  | '--ds-surface-brand-color'
  | '--ds-surface-brand-color-active'
  | '--ds-surface-brand-color-hover'
  | '--ds-surface-brand-light-color'
  | '--ds-surface-brand-pale-color'
  | '--ds-surface-danger-color'
  | '--ds-surface-danger-pale-color'
  | '--ds-surface-neutral-light-color'
  | '--ds-surface-neutral-light-color-active'
  | '--ds-surface-neutral-light-color-disabled'
  | '--ds-surface-neutral-light-color-hover'
  | '--ds-surface-neutral-pale-color'
  | '--ds-surface-neutral-pale-color-hover'
  | '--ds-surface-overlay-static-color'
  | '--ds-surface-pure-color'
  | '--ds-surface-success-color'
  | '--ds-surface-success-pale-color'
  | '--ds-surface-transparent-color'
  | '--ds-surface-warning-color'
  | '--ds-text-brand-color'
  | '--ds-text-brand-color-active'
  | '--ds-text-brand-color-disabled'
  | '--ds-text-brand-color-hover'
  | '--ds-text-color'
  | '--ds-text-color-disabled'
  | '--ds-text-inversed-color'
  | '--ds-text-inversed-static-color'
  | '--ds-text-soft-color'
  | '--ds-text-static-color'
  | '--ds-textcase-none'
  | '--ds-textdecoration-none'
  | '--ds-typography-body-l-fontfamily'
  | '--ds-typography-body-l-fontsize'
  | '--ds-typography-body-l-fontweight'
  | '--ds-typography-body-l-letterspacing'
  | '--ds-typography-body-l-lineheight'
  | '--ds-typography-body-l-paragraphindent'
  | '--ds-typography-body-l-paragraphspacing'
  | '--ds-typography-body-l-textcase'
  | '--ds-typography-body-l-textdecoration'
  | '--ds-typography-body-m-fontfamily'
  | '--ds-typography-body-m-fontsize'
  | '--ds-typography-body-m-fontweight'
  | '--ds-typography-body-m-letterspacing'
  | '--ds-typography-body-m-lineheight'
  | '--ds-typography-body-m-paragraphindent'
  | '--ds-typography-body-m-paragraphspacing'
  | '--ds-typography-body-m-textcase'
  | '--ds-typography-body-m-textdecoration'
  | '--ds-typography-body-s-b-fontfamily'
  | '--ds-typography-body-s-b-fontsize'
  | '--ds-typography-body-s-b-fontweight'
  | '--ds-typography-body-s-b-letterspacing'
  | '--ds-typography-body-s-b-lineheight'
  | '--ds-typography-body-s-b-paragraphindent'
  | '--ds-typography-body-s-b-paragraphspacing'
  | '--ds-typography-body-s-b-textcase'
  | '--ds-typography-body-s-b-textdecoration'
  | '--ds-typography-body-s-fontfamily'
  | '--ds-typography-body-s-fontsize'
  | '--ds-typography-body-s-fontweight'
  | '--ds-typography-body-s-letterspacing'
  | '--ds-typography-body-s-lineheight'
  | '--ds-typography-body-s-paragraphindent'
  | '--ds-typography-body-s-paragraphspacing'
  | '--ds-typography-body-s-textcase'
  | '--ds-typography-body-s-textdecoration'
  | '--ds-typography-body-xs-fontfamily'
  | '--ds-typography-body-xs-fontsize'
  | '--ds-typography-body-xs-fontweight'
  | '--ds-typography-body-xs-letterspacing'
  | '--ds-typography-body-xs-lineheight'
  | '--ds-typography-body-xs-paragraphindent'
  | '--ds-typography-body-xs-paragraphspacing'
  | '--ds-typography-body-xs-textcase'
  | '--ds-typography-body-xs-textdecoration'
  | '--ds-typography-heading-h2-fontfamily'
  | '--ds-typography-heading-h2-fontsize'
  | '--ds-typography-heading-h2-fontweight'
  | '--ds-typography-heading-h2-letterspacing'
  | '--ds-typography-heading-h2-lineheight'
  | '--ds-typography-heading-h2-paragraphindent'
  | '--ds-typography-heading-h2-paragraphspacing'
  | '--ds-typography-heading-h2-textcase'
  | '--ds-typography-heading-h2-textdecoration'
  | '--ds-typography-heading-h3-fontfamily'
  | '--ds-typography-heading-h3-fontsize'
  | '--ds-typography-heading-h3-fontweight'
  | '--ds-typography-heading-h3-letterspacing'
  | '--ds-typography-heading-h3-lineheight'
  | '--ds-typography-heading-h3-paragraphindent'
  | '--ds-typography-heading-h3-paragraphspacing'
  | '--ds-typography-heading-h3-textcase'
  | '--ds-typography-heading-h3-textdecoration'
  | '--ds-typography-heading-h4-fontfamily'
  | '--ds-typography-heading-h4-fontsize'
  | '--ds-typography-heading-h4-fontweight'
  | '--ds-typography-heading-h4-letterspacing'
  | '--ds-typography-heading-h4-lineheight'
  | '--ds-typography-heading-h4-paragraphindent'
  | '--ds-typography-heading-h4-paragraphspacing'
  | '--ds-typography-heading-h4-textcase'
  | '--ds-typography-heading-h4-textdecoration'
  | '--ds-typography-heading-h5-fontfamily'
  | '--ds-typography-heading-h5-fontsize'
  | '--ds-typography-heading-h5-fontweight'
  | '--ds-typography-heading-h5-letterspacing'
  | '--ds-typography-heading-h5-lineheight'
  | '--ds-typography-heading-h5-paragraphindent'
  | '--ds-typography-heading-h5-paragraphspacing'
  | '--ds-typography-heading-h5-textcase'
  | '--ds-typography-heading-h5-textdecoration'
  | '--ds-typography-heading-h6-fontfamily'
  | '--ds-typography-heading-h6-fontsize'
  | '--ds-typography-heading-h6-fontweight'
  | '--ds-typography-heading-h6-letterspacing'
  | '--ds-typography-heading-h6-lineheight'
  | '--ds-typography-heading-h6-paragraphindent'
  | '--ds-typography-heading-h6-paragraphspacing'
  | '--ds-typography-heading-h6-textcase'
  | '--ds-typography-heading-h6-textdecoration';

export type Theme = 'light' | 'dark' | 'system';

export interface ThemeTokens {
  black_0: string;
  black_100: string;
  black_1000: string;
  black_150: string;
  black_200: string;
  black_300: string;
  black_400: string;
  black_50: string;
  black_500: string;
  black_600: string;
  black_700: string;
  black_750: string;
  black_800: string;
  black_850: string;
  black_900: string;
  black_950: string;
  black_transparent: string;
  blue_ribbon_100: string;
  blue_ribbon_200: string;
  blue_ribbon_300: string;
  blue_ribbon_400: string;
  blue_ribbon_50: string;
  blue_ribbon_500: string;
  blue_ribbon_600: string;
  blue_ribbon_700: string;
  blue_ribbon_800: string;
  blue_ribbon_900: string;
  blue_ribbon_950: string;
  border_brand_color: string;
  border_brand_color_disabled: string;
  border_danger_color: string;
  border_neutral_light_color: string;
  border_neutral_soft_color: string;
  coral_red_100: string;
  coral_red_200: string;
  coral_red_300: string;
  coral_red_400: string;
  coral_red_50: string;
  coral_red_500: string;
  coral_red_600: string;
  coral_red_700: string;
  coral_red_800: string;
  coral_red_900: string;
  coral_red_950: string;
  fontfamilies_inter: string;
  fontsize_0: string;
  fontsize_1: string;
  fontsize_2: string;
  fontsize_3: string;
  fontsize_4: string;
  fontsize_5: string;
  fontsize_6: string;
  fontsize_7: string;
  fontweights_inter_0: string;
  fontweights_inter_1: string;
  fontweights_inter_2: string;
  jade_100: string;
  jade_200: string;
  jade_300: string;
  jade_400: string;
  jade_50: string;
  jade_500: string;
  jade_600: string;
  jade_700: string;
  jade_800: string;
  jade_900: string;
  jade_950: string;
  letterspacing_0: string;
  letterspacing_1: string;
  letterspacing_3: string;
  lineheights_0: string;
  lineheights_1: string;
  lineheights_2: string;
  lineheights_3: string;
  lineheights_4: string;
  lineheights_5: string;
  lineheights_6: string;
  lineheights_7: string;
  lineheights_8: string;
  lineheights_9: string;
  paragraphindent_0: string;
  pizazz_100: string;
  pizazz_200: string;
  pizazz_300: string;
  pizazz_400: string;
  pizazz_50: string;
  pizazz_500: string;
  pizazz_600: string;
  pizazz_700: string;
  pizazz_800: string;
  pizazz_900: string;
  pizazz_950: string;
  surface_brand_color: string;
  surface_brand_color_active: string;
  surface_brand_color_hover: string;
  surface_brand_light_color: string;
  surface_brand_pale_color: string;
  surface_danger_color: string;
  surface_danger_pale_color: string;
  surface_neutral_light_color: string;
  surface_neutral_light_color_active: string;
  surface_neutral_light_color_disabled: string;
  surface_neutral_light_color_hover: string;
  surface_neutral_pale_color: string;
  surface_neutral_pale_color_hover: string;
  surface_overlay_static_color: string;
  surface_pure_color: string;
  surface_success_color: string;
  surface_success_pale_color: string;
  surface_transparent_color: string;
  surface_warning_color: string;
  text_brand_color: string;
  text_brand_color_active: string;
  text_brand_color_disabled: string;
  text_brand_color_hover: string;
  text_color: string;
  text_color_disabled: string;
  text_inversed_color: string;
  text_inversed_static_color: string;
  text_soft_color: string;
  text_static_color: string;
  textcase_none: string;
  textdecoration_none: string;
  typography_body_l_fontfamily: string;
  typography_body_l_fontsize: string;
  typography_body_l_fontweight: string;
  typography_body_l_letterspacing: string;
  typography_body_l_lineheight: string;
  typography_body_l_paragraphindent: string;
  typography_body_l_paragraphspacing: string;
  typography_body_l_textcase: string;
  typography_body_l_textdecoration: string;
  typography_body_m_fontfamily: string;
  typography_body_m_fontsize: string;
  typography_body_m_fontweight: string;
  typography_body_m_letterspacing: string;
  typography_body_m_lineheight: string;
  typography_body_m_paragraphindent: string;
  typography_body_m_paragraphspacing: string;
  typography_body_m_textcase: string;
  typography_body_m_textdecoration: string;
  typography_body_s_b_fontfamily: string;
  typography_body_s_b_fontsize: string;
  typography_body_s_b_fontweight: string;
  typography_body_s_b_letterspacing: string;
  typography_body_s_b_lineheight: string;
  typography_body_s_b_paragraphindent: string;
  typography_body_s_b_paragraphspacing: string;
  typography_body_s_b_textcase: string;
  typography_body_s_b_textdecoration: string;
  typography_body_s_fontfamily: string;
  typography_body_s_fontsize: string;
  typography_body_s_fontweight: string;
  typography_body_s_letterspacing: string;
  typography_body_s_lineheight: string;
  typography_body_s_paragraphindent: string;
  typography_body_s_paragraphspacing: string;
  typography_body_s_textcase: string;
  typography_body_s_textdecoration: string;
  typography_body_xs_fontfamily: string;
  typography_body_xs_fontsize: string;
  typography_body_xs_fontweight: string;
  typography_body_xs_letterspacing: string;
  typography_body_xs_lineheight: string;
  typography_body_xs_paragraphindent: string;
  typography_body_xs_paragraphspacing: string;
  typography_body_xs_textcase: string;
  typography_body_xs_textdecoration: string;
  typography_heading_h2_fontfamily: string;
  typography_heading_h2_fontsize: string;
  typography_heading_h2_fontweight: string;
  typography_heading_h2_letterspacing: string;
  typography_heading_h2_lineheight: string;
  typography_heading_h2_paragraphindent: string;
  typography_heading_h2_paragraphspacing: string;
  typography_heading_h2_textcase: string;
  typography_heading_h2_textdecoration: string;
  typography_heading_h3_fontfamily: string;
  typography_heading_h3_fontsize: string;
  typography_heading_h3_fontweight: string;
  typography_heading_h3_letterspacing: string;
  typography_heading_h3_lineheight: string;
  typography_heading_h3_paragraphindent: string;
  typography_heading_h3_paragraphspacing: string;
  typography_heading_h3_textcase: string;
  typography_heading_h3_textdecoration: string;
  typography_heading_h4_fontfamily: string;
  typography_heading_h4_fontsize: string;
  typography_heading_h4_fontweight: string;
  typography_heading_h4_letterspacing: string;
  typography_heading_h4_lineheight: string;
  typography_heading_h4_paragraphindent: string;
  typography_heading_h4_paragraphspacing: string;
  typography_heading_h4_textcase: string;
  typography_heading_h4_textdecoration: string;
  typography_heading_h5_fontfamily: string;
  typography_heading_h5_fontsize: string;
  typography_heading_h5_fontweight: string;
  typography_heading_h5_letterspacing: string;
  typography_heading_h5_lineheight: string;
  typography_heading_h5_paragraphindent: string;
  typography_heading_h5_paragraphspacing: string;
  typography_heading_h5_textcase: string;
  typography_heading_h5_textdecoration: string;
  typography_heading_h6_fontfamily: string;
  typography_heading_h6_fontsize: string;
  typography_heading_h6_fontweight: string;
  typography_heading_h6_letterspacing: string;
  typography_heading_h6_lineheight: string;
  typography_heading_h6_paragraphindent: string;
  typography_heading_h6_paragraphspacing: string;
  typography_heading_h6_textcase: string;
  typography_heading_h6_textdecoration: string;
}
